### ISSUE TITLE
Error in library(reshape) : there is no package called ‘reshape’

### ISSUE THREAD

**Issue by tupton** [bamos/zsh-history-analysis#4]
On OS X 10.10.1 after installing python3, R, and ggplot2 as described in the readme:

```
❯ ./plot.r
Loading required package: methods
Error in library(reshape) : there is no package called ‘reshape’
Execution halted
```

**Comment by tupton** [comment]
I took a guess at this and managed to fix it by running `install.packages("reshape")` from an R shell.

**Comment by bamos** [comment]
Thanks @tupton, added.
